### ISSUE TITLE
Create the dealer

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#11]
# Dealer
The dealer should create a new card deck shuffled and returns X amount of cards. 
This dealer cannot reset after return but needs to be obviously a generator function.

The dealer takes in the parameters
* Shuffle deck
* int X amount of cards to return
* reset deck to full

## TODO
- [x] Create new deck of 52 cards shuffled
- [x] Return X amount of cards
- [x] Taken the parameter reset and create new shuffled deck

## Time
Estimated time: 00:45
Completed time interval: 00:30
