### ISSUE TITLE
Asset to Poker

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#14]
# Assets
To build a gui game of poker, assets are require for poker and these asset will be for pygame. 

## TODO
- [x] Find a normal cards assets
- [x] Find a table board assets

## Extra
- [ ] Get some GUI styling interface:
  - hands
  - people silhouette
  - background for floor
  - background for gui text
