### ISSUE TITLE
Rules of Poker

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#3]
# Study different types of games
Write a document of different games.

## TODO
- [x] Research rule of poker
- [x] Write a bullet point style summary
- [x] Add it to our Wiki (meDracula is on it)

## Time
Estimated time: 02:30
Completed time interval: 04:30
