### ISSUE TITLE
Get the poker cards into pygame

### ISSUE THREAD

**Issue by Antonsen2** [meDracula/PokerAI#31]
## TODO 
- [x] Rezise them to a good size
- [x] Get them into pygame
- [x] put them at the right place

## Time
Estimated time: 06:00
Completed time interval: hh:mm
