### ISSUE TITLE
Improve poker class documentation

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#35]
# Poker Documentation
The poker is a vital part of this project meaning some proper or at least some documentation should exist for how to use it.
## TODO
- [x]  Add doc sting to ever import function
- [x] Add good comments for what goes on internally in each function
- [x] Recheck the docstring.

## Time
Estimated time: 01:10
Completed time interval: 01:15
