### ISSUE TITLE
Tune and Tweak Poker package

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#36]
# Improving poker package
Going through the code finding unwanted or
unnecessary variable and operation and just...
tuning it and tweaking it. 

## TODO
- [x] expand imports
- [x] Change Template_deck to immutable
- [x] Change player_new to player_add
- [x] Fix player_leave bug:
  - Altered all player to dict
- [x] Timeit with different search and sort method to code
- [x] Sorting method for player folds:
  - due to Timeit showing quicker execution time

## Time
Estimated time: 04:00
Completed time interval: hh:mm
