### ISSUE TITLE
Monte Carlo CFR

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#43]
# Monte Carlo CFR
Learn/Study on Monte Carlo CFR algorithm for using with as a reinforcement algorithm for the poker ai.

## TODO
- [x] Research it
- [x] Write a in depth jupyter notebook on algorithm:
  - [x] Rock, Paper, Scissors
  - [x] Kuhn Poker
- [x] Create a implementation plan
- [x] Proofread

## Time
Estimated time: 7 days
Completed time interval: unknown
