### ISSUE TITLE
Work on bugs in pygame

### ISSUE THREAD

**Issue by MahboubehAzizzadeh** [meDracula/PokerAI#46]
## TODO 
En list av buggar:
- [X] Om man har valt ett större antal spelare så går det inte att starta ett nytt spel för mindre antal. T.ex. från 4 till 3. Det visades fortfarande 4 spelare, korten från det gamla spelet var kvar för player4 men nya kort delades för 3 players.
- [X]    När ”new game” är klickat så skall alla kort försvinna innan ”number of player” visas.
- [x]    När alla 5 ”community cards” är delade så skall en ”call” vara tillåtet och inte mer. 
- [X]    Community cards är dubbla för 4 players.
- [x]     ”Fold” fungerar inte rätt.
- [X]     När man startar pygame och spelar med t.ex. 2 spelare och spelet är klart, går det inte att starta ett nytt spel. Man måste starta om pygame.
- [X]     Om första spelare gör fold direkt innan community cards finns så kraschar spelet.
- [x]     När detta medelande "Player name is not playing a match!",  visas så kraschar pygame.
