### ISSUE TITLE
Training Loop

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#65]
# Training loop
In this loop 

## TODO
- [x] Create a epoch of the game
- [x] Import Neural Network and setup training
- [x] Make sure everything works for training
- [x] Save model

## Time
Estimated time: 1 day
Completed time interval: 2 days
