### ISSUE TITLE
Neural Network class

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#66]
# Neural Network class
This class is the feed forward neural network.

## TODO
- [x] Create __init__ Neural Network:
  - [x] Create/decide on how many layers are need & neurons
- [x] Create forward function

## Time
Estimated time: hh:mm
Completed time interval: hh:mm
