### ISSUE TITLE
Test play feedforward neural network in pygame

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#67]
# Play test Neural net model
Load in a trained Neural network model and play it on pygame

## TODO
- [x] Connect middle to pokerai class
- [x] Variable converter/interpretation for neural net of game status
- [x] Return Action from neural net

> **NOTE** This issue is dependent on #71 

## Time
Estimated time: 01:45
Completed time interval: 01:08
