### ISSUE TITLE
Determine winner function

### ISSUE THREAD

**Issue by meDracula** [meDracula/PokerAI#8]
# The winner is...
Given all new player cards and the community cards. Return the winner

## TODO 
- [x] Determine correct sorting algorithm
- [x] Compare each players hand and sort it.
- [x] Return the winner player

## Time
Estimated time: 16:00
Completed time interval: 08:00

**Comment by MahboubehAzizzadeh** [comment]
@meDracula why did u add the bug and invalid lables? Some more explanation? Did you install the treys library?

**Comment by meDracula** [comment]
Yes but there is a issue in how you convert cards ?

**Comment by MahboubehAzizzadeh** [comment]
What is the issue? How did you test it? :D Would love to know it. Shouldnt we discuss it at a meeting instead?

**Comment by meDracula** [comment]
Problem is that when I am running this code snippet
```python
p1, p2 = Player(), Player()
table = Table(p1, p2)
table.preflop()
score = Scorer(table)
score.convert_cards(table.dealer.deck())
score.get_winner()
```

OUTPUT:
score.convert_cards(table.dealer.deck)
trey_cards.append(Cards.new(cards)
rank_int = Card.CHAR_RANK_TO_INT_RANK[rank_char]
KeyError: 'D'

**Comment by MahboubehAzizzadeh** [comment]
@meDracula where did you get the class Player from? Maybe you can send the code you have, for right now we dont have any class called Player.

**Comment by meDracula** [comment]
It is not the player class the error comes from treys not begin able. 
Have you got manage to convert the dealer deck?
And if so can you show how you.
Because the error is that our deck is not compatible with his.
Therefore key error on the cards.

Anyway here is a full code dump since you asked.
```python
class Player:
    def __init__(self):
        self.cards = []

class Scorer:
    def __init__(self, table):
        self.table = table
        self.evaluator = Evaluator()

    # convert to trey library Card class
    def convert_cards(self, cards):
        trey_cards = []
        for card in cards:
            trey_cards.append(Card.new(card))
        return trey_cards

    def get_winner(self):
        player_scores = {}
        for player in self.table.players:
            player_score = self.evaluator.evaluate(self.convert_cards(self.table.community_cards), self.convert_cards(player.cards))
            player_scores[player] = player_score

        return min(player_scores, key=player_scores.get)  # return player with best score (lower scores are better)

if __name__ == '__main__':
    p1, p2 = Player(), Player()
    table = Table(p1, p2)
    table.preflop()
    print(p1.cards, p2.cards)
    score = Scorer(table)
    score.get_winner()
```

OUTPUT:
score.get_winner()
player_score = self.evaluator.evaluate/self.convert_cards(self.table.commmunity_cards), self.convert_trey_cards.append(Card.new(card))
rank_int = Card. CHAR_RANK_TO_INT_RANK[rank_char]

**KeyError: 'Kh'**

**Comment by MahboubehAzizzadeh** [comment]
@meDracula 
First error KeyError: 'D' came from _def init_deck_ in your code, we should have "Q" instead, queen and not dam :P
I had to debug to fix the code, I thought we are going to do debug as a new backlog item so I waited with debugging. Because we need to change all of our code to adapt it to find the winner. I did some changes in your code, both in "table" and your code to help python to give me the winner.

What I changed in your code Albin was D to Q  
what I changed in "table": 
   line14 **player.cards = self.dealer.deal(2)**
and so on for the rest of methods, lines 17, 20 and 23

Python didnt like it when we created list in list,  like this: [[ ]] so I changed the code.

Something else was missing in your test, you called table.preflop(), but not table.flop(). Therefore community_cards became empty.

IT WORKS NOW!
I swear to Jesus not to work until Tuesday :D
